# Generated by Django 5.0.7 on 2024-08-06 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_booking_seats_booked_remove_driver_car_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_details',
            field=models.CharField(default='no details avai', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
