# Generated by Django 5.0.7 on 2024-08-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_confirmed_booking_vehicle_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AddField(
            model_name='route',
            name='end_location',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='start_location',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
